### PR TITLE
Multiple summons choice

### PR DESCRIPTION
**Pull request by KoiKomei**
What this adds:
- Multiple summons choices.
- Summons are searched in order of pick.
- Clicking again on a summon will remove it from the list.

Known bugs:
- Removing all the summons, after adding them, will leave an empty list but still give an "ok" to the bot to start. It should turn to false.
- Summons of different types (like Water, Misc and Light) can be picked but the bot searches only for the last element that has been chosen : Leviathan Omega, Kaguya, Luminiera Omega will result in light tab being picked so the first 2 summons search will always fail. (Maybe add a check that only same type summons can be picked?)
- Nightmare quests, dimensional halo and dread barrage foes are untested but they should give problems since they use Strings and not Lists of Strings for the summons right now.

### CODE REVIEW

**Comment by steve1316** [comment]
Just added some commits of my own to your work and fixed the known bugs that you have listed out. In summary:

- Fixed bug where having an empty list of Summons made the frontend think it was ready to start.
- From now on, the bot will search one Summon at a time. When it has reached the bottom of the Summon Selection page, it will scroll back up and then select the next Summon Element tab and then proceed to search for the next Summon.

I just realized that I forgot to fix the new bugs with Nightmare Angel Halo, Events, and Dread Barrage in regards to how Summons are handled now so I will get on that soon.

**Comment by steve1316** [comment]
Alright, updated the config.ini and any relevant logic pertaining to it to bring them in line with the new Summon Selection logic. I will leave this pull request for 1 more day to see if I account any further bugs in my testing. But so far, so good @KoiKomei 👍

**Comment by KoiKomei** [comment]
Very nice, godspeed.
I'll be testing it to find any bugs, but so far it seems to be ok.

**Comment by KoiKomei** [comment]
Found a bug:
- once you get the bot ready and then change the amount of items, the bot becomes "not ready" but it doesn't empty the summons list. Adding or removing a summon will make the bot ready.

**Comment by KoiKomei** [comment]
Fixed 2 of the problems we had.
Check the edited post above.

**Comment by steve1316** [comment]
Just posted some bug fixes that fixed:

> "once you get the bot ready and then change the amount of items, the bot becomes "not ready" but it doesn't empty the summons list. Adding or removing a summon will make the bot ready (the bot won't become ready if the list becomes empty and that's ok)."

> "After being done with Nightmare Angel Halo, it won't go back to Home or to Special Quests."

I also just realized that I posted them in your main branch instead of your develop branch. I will try to post them in your develop branch instead.

**Comment by steve1316** [comment]
Alright with that, it appears that all of the bugs that you found seems to have been fixed so far. Thank you for your work! 👍 

I'm going to leave this pull request open until the end of the day today before I do a final review of the commits and then merge the pull request.

**Comment by KoiKomei** [comment]
Perfect, good stuff as usual, godspeed.

I'll be testing it tomorrow and I'll see if I find any other bug somewhere. I'll open a new issue or a pull request in that case.

**Review by steve1316 — APPROVED** [review]

**Pull request merged**
