### PR TITLE
fix bugs for and add features for generic V2

### PR DESCRIPTION
**Pull request by r0ngk**
## Bug fix:
1. scroll from home use none coordinate
2. default behaviour of script not specify #184 
## Features:
1. add enable auto in ready page
2. complete more combat script action from original
3. custom wait time after clicking a button

### CODE REVIEW

**Comment by r0ngk** [comment]
fix issues #186

**Comment by AthTop** [comment]
Skill selecting seems to not work. It selects character fine, then clicks between skills 2-3 and goes off to the next command.

**Comment by steve1316** [comment]
> Skill selecting seems to not work. It selects character fine, then clicks between skills 2-3 and goes off to the next command.

@AthTop, just to confirm was this with GenericV2 or was this seen in other Farming Modes?

**Comment by AthTop** [comment]
It was with GenericV2 yes. 
Main window was on the far left, with sub window being to main window's right side.

**Comment by r0ngk** [comment]
Issues is confirmed, working on it

**Comment by r0ngk** [comment]
Skill selecting problem solved

**Review by steve1316 — APPROVED** [review]
LGTM!

**Pull request merged**
